apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-app-config
data:
  application.properties: |
    spring.application.name=bankapp
    spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/bankappdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bankuser}
    spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bankpass123}
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
    spring.jpa.show-sql=true
